config/routes.rb
Rails.application.routes.draw do
  resources :administradors
  resources :likes
  resources :comentarios
  resources :coveets
  resources :usuarios
  resources :sessions, only: [:create, :destroy]
  root "home#index"
  
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout' 

  namespace :api, defaults: { format: 'json' }  do
    namespace :v1 do
      resources :projects, :usuarios, :coveets, :comentarios, :likes
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/coveet.rb
class Coveet < ApplicationRecord
  belongs_to :usuario

  validates :cuerpo, length: {minimum: 2}
end

app/controllers/api/v1/coveets_controller.rb
module Api
module V1
  class CoveetsController < ApplicationController

skip_before_action :verify_authenticity_token

def show
      @coveet = Coveet.find_by(id: params[:id])
      if (@coveet!=nil)
        render json: @coveet, status: :ok
  else
       render json: :nothing, status: :not_found
    end
end

def index
        render json: Coveet.all, status: :ok
end

def update
 @coveet = Coveet.find_by(id: params[:id])

  if @coveet.update(coveet_params)
        render json: @coveet, status: :ok
      else
        render json: @coveet.errors, status: :unprocessable_entity
      end
end

def create
    @coveet = Coveet.new(coveet_params)

      if @coveet.save
        render json: @coveet, status: :created
      else
        render json: @coveet.errors, status: :unprocessable_entity
      end
end

private
def coveet_params
      params.require(:coveet).permit(:cuerpo, :usuario_id, :likes)
end
end
end
end

app/controllers/coveets_controller.rb
class CoveetsController < ApplicationController
  before_action :set_coveet, only: %i[ show edit update destroy ]

  # GET /coveets or /coveets.json
  def index
    @coveets = Coveet.all
  end

  # GET /coveets/1 or /coveets/1.json
  def show
  end

  # GET /coveets/new
  def new
    @coveet = Coveet.new
  end

  # GET /coveets/1/edit
  def edit
  end

  # POST /coveets or /coveets.json
  def create
    @coveet = Coveet.new(coveet_params)

    respond_to do |format|
      if @coveet.save
        format.html { redirect_to @coveet, notice: "Coveet was successfully created." }
        format.json { render :show, status: :created, location: @coveet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coveet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coveets/1 or /coveets/1.json
  def update
    respond_to do |format|
      if @coveet.update(coveet_params)
        format.html { redirect_to @coveet, notice: "Coveet was successfully updated." }
        format.json { render :show, status: :ok, location: @coveet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coveet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coveets/1 or /coveets/1.json
  def destroy
    @coveet.destroy
    respond_to do |format|
      format.html { redirect_to coveets_url, notice: "Coveet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coveet
      @coveet = Coveet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coveet_params
      params.require(:coveet).permit(:cuerpo, :likes, :usuario_id)
    end
end

app/helpers/coveets_helper.rb
module CoveetsHelper
end

app/views/coveets/_form.html.erb
<head>
  <%= stylesheet_link_tag :coveets %>
</head>

<%= form_with(model: coveet) do |form| %>
  <% if coveet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coveet.errors.count, "error") %> prohibited this coveet from being saved:</h2>

      <ul>
        <% coveet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div id="formulario_coveet">
    <div class="field campo_coveet">
      <b><%= form.label :cuerpo %>: </b>
      <%= form.text_area :cuerpo %>
    </div>

    <div class="field campo_coveet">
      <b class="label"><%= form.label :likes %>: </b>
      <%= form.number_field :likes %>
    </div>

    <div class="field campo_coveet">
      <b><%= form.label :usuario_id %>: </b>
      <%= form.text_field :usuario_id %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>

<% end %>

app/views/coveets/edit.html.erb
<h1>Editing Coveet</h1>

<%= render 'form', coveet: @coveet %>

<%= link_to 'Show', @coveet %> |
<%= link_to 'Back', coveets_path %>

app/views/coveets/index.html.erb
<head>
  <%= stylesheet_link_tag :coveets %>
</head>

<p id="notice"><%= notice %></p>

<h1 class="titulo">Coveets</h1>
<%= link_to 'New Coveet', new_coveet_path %><br>

<div class="contenedor_listado">
  <div id="listado_coveets">
    <% @coveets.each do |coveet| %>
      <div class="coveet">
        <div class="header_coveet">
          <div class="user_picture">
            <%= image_tag "woman.png", :size => "50x50"%>
          </div>

          <div class="autor_coveet">
            <%= coveet.usuario.username %>
          </div>
        </div>
        <div class="cuerpo_coveet">
          <%= coveet.cuerpo %>
        </div>

        <div class="footer_coveet">
          <div class="btn_coveet">
            <%= link_to 'Edit', edit_coveet_path(coveet) %>
            <%= link_to 'Destroy', coveet, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>

          <div class="likes_coveet">
            Likes: <%= coveet.likes %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/coveets/new.html.erb
<h1>New Coveet</h1>

<%= render 'form', coveet: @coveet %>

<%= link_to 'Back', coveets_path %>

app/views/coveets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cuerpo:</strong>
  <%= @coveet.cuerpo %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @coveet.likes %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @coveet.usuario_id %>
</p>

<%= link_to 'Edit', edit_coveet_path(@coveet) %> |
<%= link_to 'Back', coveets_path %>