config/routes.rb
Rails.application.routes.draw do
  resources :administradors
  resources :likes
  resources :comentarios
  resources :coveets
  resources :usuarios
  resources :sessions, only: [:create, :destroy]
  root "home#index"
  
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout' 

  namespace :api, defaults: { format: 'json' }  do
    namespace :v1 do
      resources :projects, :usuarios, :coveets, :comentarios, :likes
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/administrador.rb
class Administrador < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true
end

app/controllers/administradors_controller.rb
class AdministradorsController < ApplicationController
  before_action :set_administrador, only: %i[ show edit update destroy ]

  # GET /administradors or /administradors.json
  def index
    @administradors = Administrador.all
  end

  # GET /administradors/1 or /administradors/1.json
  def show
  end

  # GET /administradors/new
  def new
    @administrador = Administrador.new
  end

  # GET /administradors/1/edit
  def edit
  end

  # POST /administradors or /administradors.json
  def create
    @administrador = Administrador.new(administrador_params)

    respond_to do |format|
      if @administrador.save
        format.html { redirect_to @administrador, notice: "Administrador was successfully created." }
        format.json { render :show, status: :created, location: @administrador }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @administrador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administradors/1 or /administradors/1.json
  def update
    respond_to do |format|
      if @administrador.update(administrador_params)
        format.html { redirect_to @administrador, notice: "Administrador was successfully updated." }
        format.json { render :show, status: :ok, location: @administrador }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @administrador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administradors/1 or /administradors/1.json
  def destroy
    n_admins = Administrador.count

    if n_admins > 1
      @administrador.destroy
      respond_to do |format|
        format.html { redirect_to administradors_url, notice: "Administrador was successfully destroyed." }
        format.json { head :no_content }
      end

    else
      respond_to do |format|
        format.html { redirect_to administradors_url, notice: "There must be at least one admin." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrador
      @administrador = Administrador.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def administrador_params
      params.require(:administrador).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/administradors_helper.rb
module AdministradorsHelper
end

app/views/administradors/_form.html.erb
<head>
  <%= stylesheet_link_tag :administradors %>
</head>

<%= form_with(model: administrador) do |form| %>
  <% if administrador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(administrador.errors.count, "error") %> prohibited this administrador from being saved:</h2>

      <ul>
        <% administrador.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div id="formulario_administrador">
    <div class="field contenedor_entrada">
      <b class="label"><%= form.label :email %>: </b>
      <%= form.text_field :email %>
    </div>

    <div class="field contenedor_entrada">
      <b class="label"><%= form.label :username %>: </b>
      <%= form.text_field :username %>
    </div>

    <div class="field contenedor_entrada">
      <b class="label"><%= form.label :password %>: </b>
      <%= form.password_field :password %>
    </div>

    <div class="field contenedor_entrada">
      <b class="label"><%= form.label :password_confirmation %>: </b>
      <%= form.password_field :password_confirmation %>
    </div>

    <div class="actions contenedor_entrada">
      <%= form.submit %>
    </div>
  </div>

<% end %>

app/views/administradors/edit.html.erb
<h1>Editing Administrador</h1>

<%= render 'form', administrador: @administrador %>

<%= link_to 'Show', @administrador %> |
<%= link_to 'Back', administradors_path %>

app/views/administradors/index.html.erb
<head>
  <%= stylesheet_link_tag :administradors %>
</head>
<p id="notice"><%= notice %></p>

<h1 id="titulo">Administradores</h1>
<%= link_to 'New Administrador', new_administrador_path %><br>
<div class="contenedor_listado">
 <div id="listado-administradores">
    <% @administradors.each do |administrador| %>
       <div class="administrador">
          <div class="user_picture">
            <%= image_tag "woman.png", :size => "50x50"%>
          </div>
          <div class="nombre-administrador">
            <b>Username: </b><%= administrador.username %>
          </div>
          <div class="footer_administrador">
           <div class="btn_administrador">
            <%= link_to 'Edit', edit_administrador_path(administrador) %>
            <%= link_to 'Destroy', administrador, method: :delete, data: { confirm: 'Are you sure?' } %>
           </div>
          </div>
       </div>
    <% end %>
 </div>
</div>

app/views/administradors/new.html.erb
<h1>New Administrador</h1>

<%= render 'form', administrador: @administrador %>

<%= link_to 'Back', administradors_path %>

app/views/administradors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @administrador.username %>
</p>

<%= link_to 'Edit', edit_administrador_path(@administrador) %> |
<%= link_to 'Back', administradors_path %>