config/routes.rb
Rails.application.routes.draw do
  resources :administradors
  resources :likes
  resources :comentarios
  resources :coveets
  resources :usuarios
  resources :sessions, only: [:create, :destroy]
  root "home#index"
  
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout' 

  namespace :api, defaults: { format: 'json' }  do
    namespace :v1 do
      resources :projects, :usuarios, :coveets, :comentarios, :likes
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :usuario
  belongs_to :coveet
  validates :coveet_id, uniqueness: { scope: :usuario, message: "No es posible repetir un like"}
end

app/controllers/api/v1/likes_controller.rb
module Api
module V1
  class LikesController < ApplicationController

skip_before_action :verify_authenticity_token

def show
  #@like = Like.find_by(id: params[:id])
  @likes = Like.where("usuario_id = ? AND coveet_id = ?", params[:usuario_id], params[:coveet_id])
  if (@likes!=nil)
    render json: @likes, status: :ok
  else
       render json: :nothing, status: :not_found
    end
end

def index
        render json: Like.all, status: :ok
end

def update
 @like = Like.find_by(id: params[:id])

  if @like.update(like_params)
        render json: @like, status: :ok
      else
        render json: @like.errors, status: :unprocessable_entity
      end
end

def create
    @like = Like.new(like_params)

      if @like.save
        render json: @like, status: :created
      else
        render json: @like.errors, status: :unprocessable_entity
      end
end

def destroy
    @like = Like.find_by(id: params[:id])
    if @like.destroy
      render json: :nothing, status: :ok
    else
      render json: :nothing, status: :unprocessable_entity
    end
end
private
def like_params
      params.require(:like).permit(:usuario_id, :coveet_id)
end
end
end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: %i[ show edit update destroy ]

  # GET /likes or /likes.json
  def index
    @likes = Like.all
  end

  # GET /likes/1 or /likes/1.json
  def show
  end

  # GET /likes/new
  def new
    @like = Like.new
  end

  # GET /likes/1/edit
  def edit
  end

  # POST /likes or /likes.json
  def create
    @like = Like.new(like_params)

    respond_to do |format|
      if @like.save
        format.html { redirect_to @like, notice: "Like was successfully created." }
        format.json { render :show, status: :created, location: @like }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /likes/1 or /likes/1.json
  def update
    respond_to do |format|
      if @like.update(like_params)
        format.html { redirect_to @like, notice: "Like was successfully updated." }
        format.json { render :show, status: :ok, location: @like }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /likes/1 or /likes/1.json
  def destroy
    @like.destroy
    respond_to do |format|
      format.html { redirect_to likes_url, notice: "Like was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_like
      @like = Like.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def like_params
      params.require(:like).permit(:usuario_id, :coveet_id)
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_form.html.erb
<%= form_with(model: like) do |form| %>
  <% if like.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(like.errors.count, "error") %> prohibited this like from being saved:</h2>

      <ul>
        <% like.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :usuario_id %>
    <%= form.text_field :usuario_id %>
  </div>

  <div class="field">
    <%= form.label :coveet_id %>
    <%= form.text_field :coveet_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/likes/edit.html.erb
<h1>Editing Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Show', @like %> |
<%= link_to 'Back', likes_path %>

app/views/likes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Likes</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Coveet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @likes.each do |like| %>
      <tr>
        <td><%= like.usuario_id %></td>
        <td><%= like.coveet_id %></td>
        <td><%= link_to 'Show', like %></td>
        <td><%= link_to 'Edit', edit_like_path(like) %></td>
        <td><%= link_to 'Destroy', like, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Like', new_like_path %>

app/views/likes/new.html.erb
<h1>New Like</h1>

<%= render 'form', like: @like %>

<%= link_to 'Back', likes_path %>

app/views/likes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @like.usuario_id %>
</p>

<p>
  <strong>Coveet:</strong>
  <%= @like.coveet_id %>
</p>

<%= link_to 'Edit', edit_like_path(@like) %> |
<%= link_to 'Back', likes_path %>